version: "2"

run:
  timeout: 5m
  tests: true

linters:
  default: standard
  enable:
    - durationcheck
    - errname
    - errorlint
    - nilerr
    - nilnesserr
    - nolintlint
    - predeclared
    - revive
  settings:
    nolintlint:
      require-explanation: true
      require-specific: true
    revive:
      enable-default-rules: false
      rules:
        - name: exported
        - name: package-comments
        - name: context-as-argument
        - name: error-return
  exclusions:
    presets: []

formatters:
  enable:
    - gci
    - gofumpt
    - goimports
    - golines
